services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USERNAME=todo
      - POSTGRES_PASSWORD=todo
      - POSTGRES_DB=todo
    ports:
      - 5432:5432
    volumes:
      - .docker/postgres:/docker-entrypoint-initdb.d